// <auto-generated />
using ECoreHyperdrive.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECoreHyperdrive.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306160925_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("ECoreHyperdrive.Models.Supercar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("RangeKm")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ZeroToHundred")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Supercars");
                });
#pragma warning restore 612, 618
        }
    }
}
